import './globals.css';
import styles from './layout.module.css';

export const metadata = {
	title: 'NFT details',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<main className={styles.main}>
					{children}
				</main>
			</body>
		</html>
	);
}
